package com.example.ui.utils

object AppLocalization {
    fun t(key: String, isIndonesian: Boolean): String {
        return if (isIndonesian) {
            when (key) {
                // Navigation & Headers
                "nav_tools" -> "Alat"
                "nav_notes" -> "Catatan"
                "nav_work" -> "Pekerjaan"
                "nav_camera" -> "Kamera & AR"
                "nav_calculator" -> "Kalkulator"
                "nav_library" -> "Pustaka"
                "nav_ai" -> "AI Copilot"
                "scientific_calc" -> "Kalkulator Ilmiah"
                "unit_converter" -> "Konverter Satuan"
                "tool_catalog" -> "Katalog Alat"
                "customize_dashboard" -> "Sesuaikan Beranda"
                "offline_sync" -> "Pusat Sinkronisasi Offline"
                "app_settings" -> "Pengaturan Aplikasi"
                "app_title" -> "Brillian Tools"

                // Welcome Screen
                "welcome_title" -> "Brillian Tools Suite"
                "welcome_subtitle" -> "Buku pegangan utilitas pertukangan terbaik yang ada di saku Anda."
                "welcome_bullet1_title" -> "Ruang Kerja Alat Adaptif"
                "welcome_bullet1_desc" -> "Lebih dari 50+ alat kalkulasi yang diatur secara dinamis untuk bidang Anda."
                "welcome_bullet2_title" -> "Mesin Sinkronisasi Utilitas Offline"
                "welcome_bullet2_desc" -> "Bekerja sepenuhnya offline di ruang bawah tanah atau lokasi terpencil. Sinkronisasi mulus saat sinyal kembali."
                "welcome_bullet3_title" -> "Pelacakan Log Berkelanjutan"
                "welcome_bullet3_desc" -> "Simpan catatan perhitungan, inventaris material, dan catatan situs kerja secara otomatis."
                "welcome_terms_title" -> "Ketentuan Referensi"
                "welcome_terms_desc" -> "Harap baca dan setujui pedoman berikut untuk melanjutkan instalasi."
                "welcome_terms_body" -> "1. Perhitungan dan Estimasi:\nAplikasi ini menyediakan utilitas estimasi, perhitungan, rumus konversi, dan pembacaan sensor untuk pertukangan kayu, teknik sipil, instalasi listrik, perpipaan, dan bidang terkait konstruksi lainnya. Semua perhitungan didasarkan pada rumus standar.\n\n2. Verifikasi Profesional:\nWalaupun kami mengupayakan presisi matematika yang tinggi, nilai yang dihasilkan oleh alat ini hanya untuk tujuan estimasi. Pengguna harus memverifikasi semua dimensi struktural bangunan, margin keselamatan, batasan beban, dan kode kelistrikan dengan rencana profesional dan pedoman resmi.\n\n3. Akurasi Sensor:\nFitur sensor (seperti altimeter, kompas, tingkat suara desibel, level) bergantung langsung pada sensor perangkat keras di perangkat seluler Anda. Akurasi dapat bervariasi tergantung pada interferensi magnetik lingkungan, suhu, dan kualitas perangkat keras."
                "welcome_terms_checkbox" -> "Saya menyetujui Ketentuan Referensi dan mengetahui bahwa perhitungan harus diverifikasi di lapangan."
                "welcome_permissions_title" -> "Izin Perangkat"
                "welcome_permissions_desc" -> "Brillian Tools memanfaatkan perangkat keras modern untuk meningkatkan perhitungan. Berikut yang kami gunakan:"
                "welcome_perm1_title" -> "Lokasi Presisi"
                "welcome_perm1_desc" -> "Diperlukan untuk meteorologi lokal langsung, perhitungan surya jalur matahari, dan referensi altimeter barometrik."
                "welcome_perm2_title" -> "Kamera & Kedalaman AR"
                "welcome_perm2_desc" -> "Digunakan oleh alat pengukuran AR, hamparan pembidik level pipa, dan pencatatan inventaris kode batang."
                "welcome_perm3_title" -> "Sensor Mikrofon"
                "welcome_perm3_desc" -> "Memberi makan Pengukur Suara Desibel dan diagnostik mesin akustik untuk getaran mesin."
                "welcome_settings_title" -> "Pengaturan Pengukuran"
                "welcome_settings_desc" -> "Konfigurasikan standar pilihan untuk perhitungan. Anda dapat mengubahnya di pengaturan kapan saja."
                "welcome_unit_system" -> "Sistem Satuan Pilihan"
                "welcome_imperial_label" -> "Imperial"
                "welcome_imperial_desc" -> "Inci, Kaki, Yard, Lbs"
                "welcome_metric_label" -> "Metrik"
                "welcome_metric_desc" -> "Milimeter, Meter, Kg"
                "welcome_precision_title" -> "Presisi Pengukuran Pita"
                "welcome_profile_title" -> "Pilih Profil Ruang Kerja Anda"
                "welcome_profile_desc" -> "Kami akan menyematkan utilitas perhitungan paling penting berdasarkan tugas harian Anda. Anda dapat menyesuaikannya nanti kapan saja dari Katalog Alat."
                "welcome_ai_title" -> "Unduh AI Copilot di Perangkat"
                "welcome_ai_desc" -> "Aktifkan model asisten perdagangan lokal di perangkat (bobot GGUF). Jalankan sepenuhnya offline di lokasi kerja tanpa penundaan seluler."
                "welcome_ai_no_weights" -> "Status: Belum ada bobot lokal yang diunduh."
                "welcome_ai_downloading" -> "Mengunduh & mengompilasi bobot..."
                "welcome_ai_btn_download" -> "Unduh Qwen2.5 1.5B (920 MB)"
                "welcome_ai_ready" -> "siap di perangkat!"
                "welcome_ai_btn_delete" -> "Hapus Model Aktif untuk Membebaskan Penyimpanan"
                "btn_back" -> "Kembali"
                "btn_next" -> "Lanjut"
                "btn_get_started" -> "Mulai"

                // Profile titles & descriptions (ID)
                "profile_woodworker_title" -> "Tukang Kayu"
                "profile_woodworker_sub" -> "Pekerjaan Kayu & Pertukangan"
                "profile_woodworker_desc" -> "Estimasi papan, optimasi pola potong, templat tangga, sudut gergaji miter, dan skala kelembapan."

                "profile_civil_title" -> "Ahli Teknik Sipil"
                "profile_civil_sub" -> "Penggalian, Beton & Ketinggian"
                "profile_civil_desc" -> "Volume beton, galian/urukan tanah, kemiringan, perhitungan limpasan air hujan, dan ayakan agregat."

                "profile_electrician_title" -> "Ahli Listrik"
                "profile_electrician_sub" -> "Kelistrikan & Pengawatan"
                "profile_electrician_desc" -> "Hukum Ohm, penurunan tegangan, kapasitas konduit, arus motor, panel pemutus, dan pengukur baterai."

                "profile_mechanical_title" -> "Mekanikal & HVAC"
                "profile_mechanical_sub" -> "Mekanikal, HVAC & Perpipaan"
                "profile_mechanical_desc" -> "Titik embun, bola basah, kurva refrigeran termodinamika, pengukur kecepatan saluran, dan sudut seling."

                "profile_painter_title" -> "Spesialis Pengecatan"
                "profile_painter_sub" -> "Pengecatan, Pelapisan & Persiapan"
                "profile_painter_desc" -> "Perhitungan cakupan, rasio campuran 2K, ketebalan basah, titik embun, dan perawatan karat."

                "profile_metalworker_title" -> "Ahli Logam & Pengelasan"
                "profile_metalworker_sub" -> "Pengelasan, Pabrikasi & Logam"
                "profile_metalworker_desc" -> "Parameter las, masukan panas, ekivalen karbon, K-faktor tekuk plat, unfoler kerucut, dan geometri sambungan."

                "profile_general_title" -> "Kontraktor Umum"
                "profile_general_sub" -> "Pemeliharaan Umum & Tukang"
                "profile_general_desc" -> "Penghitungan drywall, pemasangan ubin, cakupan cat, alat ukur umum, dan daftar periksa."

                // Settings & Preferences
                "settings_title" -> "PENGATURAN APLIKASI & PREFERENSI"
                "settings_subtitle" -> "Satuan, Bahasa, Tema & Sinkronisasi Cuaca"
                "language_label" -> "Bahasa Antarmuka (Language)"
                "unit_system_label" -> "Sistem Satuan & Pengukuran"
                "imperial" -> "Imperial (Inci / Kaki / PSI)"
                "metric" -> "Metrik (Meter / cm / kg)"
                "outdoor_theme" -> "Tema Tampilan Luar Ruangan"
                "light_mode_outdoor" -> "Mode Terang (Direkomendasikan di Lapangan)"
                "light_mode_desc" -> "Maksimalkan kontras layar di bawah terik matahari langsung pada proyek konstruksi."
                "high_contrast_colors" -> "Warna Kontras Tinggi"
                "high_contrast_desc" -> "Meningkatkan garis batas kartu dan ketebalan huruf di luar ruangan."
                "weather_provider" -> "Penyedia Cuaca & Lingkungan Situs"
                "precision_label" -> "Presisi Pecahan Pengukuran"
                "gps_label" -> "GPS & Lokasi Geografis Situs"
                "currency_label" -> "Mata Uang Proyek"
                "labor_rate_label" -> "Tarif Upah Kerja Per Jam"
                "cloud_sync" -> "Sinkronisasi Cloud & Database"
                "ai_features" -> "Fitur Asisten AI Cerdas"
                "ai_features_desc" -> "Sakelar utama untuk fitur kopilot AI melayang dan analisis."
                "online_ai_provider" -> "Penyedia Cloud AI Online"
                "local_ai_title" -> "Model AI Lokal Perangkat (Offline-Ready)"
                "local_ai_desc" -> "Unduh dan jalankan bobot AI secara lokal di penyimpanan perangkat (100% aman, siap offline, tanpa biaya langganan)."
                "about_app" -> "Tentang Aplikasi & Versi"

                // Materials & Guidance
                "materials_title" -> "Material Konstruksi & Kayu Lokal Indonesia"
                "cement_label" -> "Semen: Semen Gresik, Tiga Roda (Indocement), Holcim (Solusi Bangun Indonesia), Padang"
                "brick_label" -> "Bata & Blok: Bata Merah Bakar, Batako Press Beton, Hebel AAC"
                "paint_label" -> "Cat & Pelapis: Dulux, Jotun, Avitex, Catylac, Nippon Paint, Mowilex"
                "chemicals_label" -> "Bahan Kimia & Waterproofing: SikaTop Seal 107, Aquaproof, SikaLatex"
                "safety_standards" -> "Standar Keselamatan: SNI (Standar Nasional Indonesia), K3 Konstruksi (Keselamatan & Kesehatan Kerja)"
                "local_woods" -> "Kayu Lokal Unggulan: Jati, Mahoni, Albasia/Sengon, Waru, Keruing, Nangka, Cengkih, Merbau, Ulin (Ironwood), Bangkirai, Sonokeling, Sungkai"

                // Common buttons / hints
                "search_hint" -> "Cari model 3D, SKP, DWG, denah, atau dokumen..."
                "save" -> "Simpan"
                "cancel" -> "Batal"
                "calculate" -> "Hitung"
                "reset" -> "Atur Ulang"
                "export" -> "Ekspor Laporan"
                else -> key
            }
        } else {
            when (key) {
                // Navigation & Headers
                "nav_tools" -> "Tools"
                "nav_notes" -> "Notes"
                "nav_work" -> "Work"
                "nav_camera" -> "Camera & AR"
                "nav_calculator" -> "Calculator"
                "nav_library" -> "Library"
                "nav_ai" -> "AI Copilot"
                "scientific_calc" -> "Scientific Calc"
                "unit_converter" -> "Unit Converter"
                "tool_catalog" -> "Tool Catalog"
                "customize_dashboard" -> "Customize Dashboard"
                "offline_sync" -> "Offline Sync Center"
                "app_settings" -> "App Settings"
                "app_title" -> "Brillian Tools"

                // Welcome Screen
                "welcome_title" -> "Brillian Tools Suite"
                "welcome_subtitle" -> "The ultimate trade utility handbook built right into your pocket."
                "welcome_bullet1_title" -> "Adaptive Tool Workspace"
                "welcome_bullet1_desc" -> "Over 50+ calculation tools organized dynamically for your trade."
                "welcome_bullet2_title" -> "Offline-First Sync Engine"
                "welcome_bullet2_desc" -> "Work completely offline in deep basement garages or remote sites. Syncs seamlessly whenever signal returns."
                "welcome_bullet3_title" -> "Continuous Log Tracking"
                "welcome_bullet3_desc" -> "Keep records of your calculations, materials inventory, and job site notes automatically."
                "welcome_terms_title" -> "Terms of Reference"
                "welcome_terms_desc" -> "Please read and accept the following guidelines to proceed with installation."
                "welcome_terms_body" -> "1. Calculations and Estimates:\nThis application provides estimation utilities, calculations, conversion formulas, and sensor readings for woodworking, civil engineering, electrical works, plumbing, and other construction-related trades. All computations are based on typical standard code formulas. \n\n2. Professional Verification:\nWhile we strive for extreme mathematical precision, values produced by these tools are for estimation purposes only. Users must verify all critical building structural dimensions, safety margins, load constraints, and electrical codes with professional plans and official code guidelines.\n\n3. Sensor Accuracy:\nSensor features (e.g. altimeter, compass, decibel level, leveler) rely directly on hardware sensors on your mobile device. Accuracy may vary depending on environmental magnetic interference, temperature, and device hardware quality."
                "welcome_terms_checkbox" -> "I accept the Terms of Reference and acknowledge that calculations should be verified on-site."
                "welcome_permissions_title" -> "Device Permissions"
                "welcome_permissions_desc" -> "Brillian Tools utilizes modern device hardware to enhance calculations. Here is what we use:"
                "welcome_perm1_title" -> "Precise Location"
                "welcome_perm1_desc" -> "Required for live local meteorology, sun-path solar calculations, and barometric altimeter referencing."
                "welcome_perm2_title" -> "Camera & AR Depth"
                "welcome_perm2_desc" -> "Used by AR measurement tools, plumbing level viewfinder overlays, and barcode inventory logging."
                "welcome_perm3_title" -> "Microphone Sensor"
                "welcome_perm3_desc" -> "Feeds the Decibel Sound Meter and acoustic engine diagnostics for machinery vibration."
                "welcome_settings_title" -> "Measurement Settings"
                "welcome_settings_desc" -> "Configure preferred standards for the calculations. You can change this in settings anytime."
                "welcome_unit_system" -> "Preferred Unit System"
                "welcome_imperial_label" -> "Imperial"
                "welcome_imperial_desc" -> "Inches, Feet, Yards, Lbs"
                "welcome_metric_label" -> "Metric"
                "welcome_metric_desc" -> "Millimeters, Meters, Kg"
                "welcome_precision_title" -> "Tape Measurement Precision"
                "welcome_profile_title" -> "Choose Your Workspace Profile"
                "welcome_profile_desc" -> "We will pre-pin the most critical calculation utilities based on your daily job desk. You can customize this later anytime from the Tool Catalog."
                "welcome_ai_title" -> "On-Device AI Copilot Download"
                "welcome_ai_desc" -> "Activate an on-device local trade assistant model (GGUF weights). Run completely offline at jobsites with zero cellular delay."
                "welcome_ai_no_weights" -> "Status: No local weights downloaded yet."
                "welcome_ai_downloading" -> "Downloading & compiling weights..."
                "welcome_ai_btn_download" -> "Download Qwen2.5 1.5B (920 MB)"
                "welcome_ai_ready" -> "is ready on-device!"
                "welcome_ai_btn_delete" -> "Delete Active Model to Free Storage"
                "btn_back" -> "Back"
                "btn_next" -> "Next"
                "btn_get_started" -> "Get Started"

                // Profile titles & descriptions (EN)
                "profile_woodworker_title" -> "Woodworker"
                "profile_woodworker_sub" -> "Woodworking & Carpentry"
                "profile_woodworker_desc" -> "Board estimation, cut-list optimization, stair templates, miter saw angles, and moisture scales."

                "profile_civil_title" -> "Civil Engineer"
                "profile_civil_sub" -> "Excavation, Concrete & Grades"
                "profile_civil_desc" -> "Concrete volumes, earthwork cut/fills, grade, stormwater runoff calculation, and aggregate sieves."

                "profile_electrician_title" -> "Electrician"
                "profile_electrician_sub" -> "Electrical & Wiring"
                "profile_electrician_desc" -> "Ohm's law, voltage drops, conduit fill capacities, motor amperes, breaker panels, and battery sizers."

                "profile_mechanical_title" -> "Mechanical & HVAC"
                "profile_mechanical_sub" -> "Mechanical, HVAC & Piping"
                "profile_mechanical_desc" -> "Dew point, wet bulb, live thermodynamic refrigerant curves, duct velocity sizers, and rigging sling angles."

                "profile_painter_title" -> "Painter & Coating Specialist"
                "profile_painter_sub" -> "Painting, Coating & Prep"
                "profile_painter_desc" -> "Coverage calculations, 2K mixing ratios, wet film thickness, dew points, and rust treatment."

                "profile_metalworker_title" -> "Metalworker & Welder"
                "profile_metalworker_sub" -> "Welding, Fabrication & Metallurgy"
                "profile_metalworker_desc" -> "Welding parameters, heat input, carbon equivalent, sheet metal bend K-factor, cone unfolders, and weld inspection."

                "profile_general_title" -> "General Contractor"
                "profile_general_sub" -> "General Maintenance & Handyman"
                "profile_general_desc" -> "Drywall count, tiling, painting coverage, general measuring tools, and checklists."

                // Settings & Preferences
                "settings_title" -> "APP SETTINGS & PREFERENCES"
                "settings_subtitle" -> "Units, Language, Theme & Weather Sync"
                "language_label" -> "Interface Language"
                "unit_system_label" -> "Unit System & Measurement"
                "imperial" -> "Imperial (Inches / Feet / PSI)"
                "metric" -> "Metric (Meters / cm / kg)"
                "outdoor_theme" -> "Outdoor Theme & Display"
                "light_mode_outdoor" -> "Light Mode (Recommended Outdoors)"
                "light_mode_desc" -> "Maximizes screen contrast under direct sunlight on jobsites."
                "high_contrast_colors" -> "High-Contrast Daylight Colors"
                "high_contrast_desc" -> "Enhances card outlines and bold typography outdoors."
                "weather_provider" -> "Weather & Site Environment Provider"
                "precision_label" -> "Measurement Fractional Precision"
                "gps_label" -> "GPS & Site Geographical Location"
                "currency_label" -> "Project Currency"
                "labor_rate_label" -> "Labor Cost Per Hour"
                "cloud_sync" -> "Cloud Sync & Database"
                "ai_features" -> "AI Assistant Features"
                "ai_features_desc" -> "Master switch for floating AI copilot and assistant features."
                "online_ai_provider" -> "Online Cloud AI Provider"
                "local_ai_title" -> "Device Local AI Weights (Offline-Ready)"
                "local_ai_desc" -> "Download and host AI weights locally on your device storage (100% secure, offline-ready, zero subscription cost)."
                "about_app" -> "About App & Version"

                // Materials & Guidance
                "materials_title" -> "Construction Materials & Indonesian Local Woods"
                "cement_label" -> "Cement: Semen Gresik, Tiga Roda (Indocement), Holcim, Padang"
                "brick_label" -> "Bricks: Red Brick, Concrete Block (Batako), Hebel AAC"
                "paint_label" -> "Paint: Dulux, Jotun, Avitex, Catylac, Nippon Paint, Mowilex"
                "chemicals_label" -> "Chemicals & Waterproofing: SikaTop Seal 107, Aquaproof, SikaLatex"
                "safety_standards" -> "Safety Standards: SNI (Indonesian National Standard), K3 Construction Safety"
                "local_woods" -> "Local Woods: Teak (Jati), Mahogany, Albasia/Sengon, Waru, Keruing, Nangka, Cengkih, Merbau, Ironwood (Ulin), Bangkirai, Sonokeling, Sungkai"

                // Common buttons / hints
                "search_hint" -> "Search 3D models, SKP, DWG, blueprints..."
                "save" -> "Save"
                "cancel" -> "Cancel"
                "calculate" -> "Calculate"
                "reset" -> "Reset"
                "export" -> "Export Report"
                else -> key
            }
        }
    }
}
